services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp123
      POSTGRES_DB: chatapp
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://chatapp:chatapp123@postgres:5432/chatapp?schema=public"
      REDIS_URL: "redis://redis:6379"
      JWT_SECRET: "your-secret-key-12345"
      NODE_ENV: "production"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data: